name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      make_release:
        description: 'True to make a release'
        required: true
        type: boolean

env:
  GO_VERSION: 1.21.1

jobs:
  # Build Job
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          wget --no-verbose "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
          rm "go${GO_VERSION}.linux-amd64.tar.gz"

      - name: Prepare APT
        run: sudo apt-get update

      - name: Install GCC
        run: sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev

      - name: Install mingw-w64
        run: sudo apt-get install -y mingw-w64

      - name: Build Windows
        run:  go run ./build/build.go --target "Compile:Windows"

      - name: Build Linux
        run:  go run ./build/build.go --target "Compile:Linux"

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: .build-output/disk-tree.exe

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: .build-output/disk-tree.tar.xz

  # Release Job
  release:
    if: ${{ inputs.make_release }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: Windows
          path: .build-output/disk-tree.exe

      - name: Download Linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: Linux
          path: .build-output/disk-tree.tar.xz

      - name: Install Go
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          wget --no-verbose "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
          rm "go${GO_VERSION}.linux-amd64.tar.gz"

      - name: Create the release
        run:  go run ./build/build.go --target "Release:Create"

